sudo: false
language: php
php:
- 7
install:
- nvm install 10
- npm install
script:
- ".travis-build/phplint ."
after_success:
- npm run build
- rm -rf node_modules
- tar -czf stories.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lTLpg2wL6bv1oRFIUs9/csN0J0n6Wya0cuQKczYL++FLNLcyg6xilDIJIn8dlfR6YtEDtMbG1aVlLBKVlfOShHEha69pPRfemcPAw6GIQssklHD72s6va84OpTG31DVxYg+KW7REYUfuwBX5dvOAS5CkZTp4sELxHNjG5zuUNPEQr2z/VX6tPInzy8+A40PsOo393ionN2kE1z1/qxiTNmZTtRKUZ8EeDbXf+I+Hm9JPBxvP5Zxkqh82a2xfDJDdigWIOHrbsbsGTMnJhiJRzQhdWsl69U2YB0EwwuDrEJZ2Bxhvb+zYNTKLV6syCXMhp0knvIbV8kmtPkDSJ5oce03INSUG6rVkPphAsohUDJNoFkbEXndjVIBwKcsyQ4aDmCkh5FEVknx65+kW97jjc7tWcwpYuKHoXK0fmVKRCYUEbGzNelXVGneImA311Ri5/ZwzEq07+oBOEjfZfIUiLQvElaGym9ez40tIt0tOl6zTIvyKbNFTUaoEtNJK+Kkw+99QpoHDkQQxmyu1TAneBkmISO1WDm73LITX5EDml8RD4D78nPgkOnmMk00zNvoJC6RSmg+k0idzXUwCiNhimEiiheuj7wo47se9rOIZcd3bLYB43cnTYu6u/pT+Dv/BoLP9qzUOgJY9l43RhV0iYaUgoU1HVp3QH+h+T48KMnE=
  file: stories.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/stories
    branch: master
    tags: true
